#!/bin/bash
# scripts/gen-terminus-embed.sh - Generate embedded Terminus TTF C source
#
# Usage: bash scripts/gen-terminus-embed.sh [TTF_FILE]
# Default: 3rdp/prefix/share/fonts/terminus-ttf/TerminusTTF.ttf

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUT_C="$REPO_ROOT/src/photonterm/photon_terminus_font.c"

# Find the TTF file
TTF="${1:-}"
if [[ -z "$TTF" ]]; then
    for candidate in \
        "$REPO_ROOT/3rdp/prefix/share/fonts/terminus-ttf/TerminusTTF.ttf" \
        "$REPO_ROOT/3rdp/prefix/share/fonts/terminus-ttf/TerminusTTF-4.49.3.ttf"; do
        if [[ -f "$candidate" ]]; then
            TTF="$candidate"
            break
        fi
    done
fi

if [[ -z "$TTF" ]] || [[ ! -f "$TTF" ]]; then
    echo "ERROR: No TTF file found. Run 'bash scripts/build-deps.sh terminus_ttf' first." >&2
    exit 1
fi

echo "Generating $OUT_C from $TTF..."

{
    cat << 'HEADER'
/* photon_terminus_font.c - Embedded Terminus TTF font data
 *
 * Terminus TTF 4.49.3 - SIL Open Font License 1.1
 * https://files.ax86.net/terminus-ttf/
 *
 * AUTO-GENERATED by scripts/gen-terminus-embed.sh
 * Do not edit manually.
 */
#include "photon_terminus_font.h"

const unsigned char photon_terminus_ttf[] = {
HEADER
    xxd -i < "$TTF" | sed 's/^/    /'
    cat << 'FOOTER'
};

const size_t photon_terminus_ttf_size = sizeof(photon_terminus_ttf);
FOOTER
} > "$OUT_C"

SIZE=$(wc -c < "$TTF" | tr -d ' ')
echo "Done: embedded $SIZE bytes from $(basename "$TTF")"
